---

- name: Install Nginx
  hosts: all
  become: true

  tasks:
    - name: Update apt cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Nginx
      package:
        name: nginx
        state: present        
      