# Dockerfile.flask
FROM ubuntu:latest

# Install Python and Flask
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install flask

# Copy Flask app
COPY app.py /app.py

# Expose port
EXPOSE 8000

# Start Flask app
CMD ["python3", "/app.py"]
