# docker-compose.yml
version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  postgresql:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
