---
- hosts: Ubuntu
  tasks:
    - name: install nginx
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
      become: true
- hosts: RedHat
  tasks:
    - name: remove nginx
      yum:
        name: nginx
        state: absent
        autoremove: yes
    - name: install httpd
      yum: name=httpd state=latest
    - name: start httpd
      service:
          name: httpd
          state: started
      become: true             